service: eventlogger


provider:
  name: aws
  runtime: nodejs4.3
  stage: "1"
  region: us-east-1
  profile: perceptionz
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

functions:
  logthis:
    handler: handler.hello
    events:
      - http:
          path: /logthis
          method: post
